### ISSUE TITLE
support for sf3

### ISSUE THREAD

**Issue by EugenDueck** [jet2jet/fluidsynth-emscripten#7]
When trying to load an sf3 file I get this error:
```
Sound font version is 3.0 but fluidsynth was compiled without support for (v3.x)
```
Is it possible to get the emscripten version of fluidsynth compiled with sf3 support?

**Comment by Zipdox** [comment]
I second this.

**Comment by Zipdox** [comment]
It appears that there is an issue with emcmake that causes CMake to not find libsndfile. This means fluidsynth gets built without Vorbis support and this without SF3 support.

**Comment by EugenDueck** [comment]
As an example, I have an sf2 file of 41MB - converted to sf3 (using Polyphone with the "high quality" setting) it is only 12MB in size. So the sf2 is 3~4 times as big. Quite a difference, especially on the web. sf2 files with more instruments can get as big as 1GB and perhaps more.

**Comment by jet2jet** [comment]
Sorry for delay response.

I released following version of `fluidsynth-emscripten`, which includes `sndfile` support:

- https://github.com/jet2jet/fluidsynth-emscripten/releases/tag/v2.2.1-em-3
- https://github.com/jet2jet/fluidsynth-emscripten/releases/tag/v2.3.0-em

I tested these and sf3 file could be loaded successfully (tested with `FluidR3Mono`).

(Note that building `flac` `ogg` `vorbis` `opus` with Emscripten is necessary to build `sndfile` with Emscripten. I think it is not too difficult.)

**Comment by Zipdox** [comment]
What's the difference between the two?

**Comment by Zipdox** [comment]
Hmmm it doesn't seem to work.
![image](https://user-images.githubusercontent.com/42157341/209682004-ffe32d5c-cfd9-4c91-a4d7-76772534ee2f.png)

**Comment by Zipdox** [comment]
Don't forget to replace the Worklet addModule call or you're gonna have a bad time lol
![image](https://user-images.githubusercontent.com/42157341/209693974-d5a7cc1b-852d-46e6-a59b-fb81a2fa25ab.png)

**Comment by EugenDueck** [comment]
Awesome. sf3 now works by changing to libfluidsynth-2.3.0-with-libsndfile.js. Great many thanks for addressing it this quickly @jet2jet !
The sf2->sf3 space savings even for my small sound font far outweigh the 1.7M increase of libfluidsynth-2.3.0-with-libsndfile.js compared to libfluidsynth-2.2.1.js.

**Comment by Zipdox** [comment]
Well, the loading time for the MuseScore basic sound font is pretty long, but I guess that's the price you have to pay.

**Comment by EugenDueck** [comment]
@Zipdox Sounds like a tradeoff - but now we have a choice between speed of loading over the net vs loading and initializing into memory. As the sound font may be cached and thus needs to be loaded over the net only once, it may in fact make sense to use sf2...
